### ISSUE TITLE
Github Source Button wrong link

### ISSUE THREAD

**Issue by vietz-dev** [Abdellatif404/flutter_notes_app#1]
Hey there :)

First of all props to you writing this app it looks very good.

I've tried it out and noticed some minor issues, so I'll create some issues.

___

If you go in the Settings and click on the Github Icon you're redirected to flutter.dev instead to your github page.

**Comment by Abdellatif404** [comment]
Thanks for alerting me to this, I will fix it right now

**Comment by Abdellatif404** [comment]
OK, I fixed the problem, so can test it now :)
