### ISSUE TITLE
LongPressing Card changes border

### ISSUE THREAD

**Issue by vietz-dev** [Abdellatif404/flutter_notes_app#2]
If i longPress a created tile which normally has a circular border it'll become rectangular.
It should stay rounded.

**Comment by Abdellatif404** [comment]
Yeah I saw that, but I didn't know how to solve it 😔

**Comment by vietz-dev** [comment]
See here 
![Anmerkung 2020-08-26 130935](https://user-images.githubusercontent.com/17956096/91296770-73637100-e79d-11ea-8f65-9ecdc8de857d.png)
vs
![image](https://user-images.githubusercontent.com/17956096/91296797-80806000-e79d-11ea-9ebd-fa811534cfff.png)

**Comment by vietz-dev** [comment]
@Abdellatif404 I don't know if I can solve it, but I'll try to look into the code :)

**Comment by Abdellatif404** [comment]
Yep, I understand the problem, I'll try to fix it soon. 👍

**Comment by Abdellatif404** [comment]
Well, I've repaired this problem, thanks for this
